// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-clear-signing.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNNativeModuleSpec.h"

@interface ClearSigning : NSObject <NativeClearSigningSpec>
#else
#import <React/RCTBridgeModule.h>

@interface ClearSigning : NSObject <RCTBridgeModule>
#endif

@end