#!/usr/bin/env bash
# Deterministically (re-)write bindings/react-native/react-native-clear-signing.podspec.
#
# `ubrn build ios` regenerates the podspec from its template every run, which
# wipes the local patches we need (renamed s.name, defined?-guarded
# min_ios_version_supported, dropped self-dependency on the JSI runtime pod,
# etc.). Run this script after `ubrn build ios` to restore the canonical shape.
#
# Usage:
#   ./scripts/prepare-rn-podspec.sh                       # local-dev shape (no prepare_command)
#   ./scripts/prepare-rn-podspec.sh <version> <sha256>    # release shape (downloads + verifies xcframework)
#
# <version> must match ^[0-9]+\.[0-9]+\.[0-9]+$ (strict semver).
# <sha256>  must match ^[0-9a-f]{64}$ (hex digest of libclear_signing-rn.xcframework.zip).
#
# Idempotent — same arguments produce the same file.

set -euo pipefail

VERSION="${1:-}"
SHA256="${2:-}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PKG_DIR="$REPO_ROOT/bindings/react-native"
PODSPEC="$PKG_DIR/react-native-clear-signing.podspec"

# Refuse anything that isn't strict semver. The version lands inside the
# podspec's prepare_command, which CocoaPods executes as shell at every
# consumer's `pod install` time — so an unsanitized version here ships an
# arbitrary command to every wallet that ever installs that release.
if [ -n "$VERSION" ] && ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "ERROR: invalid version '$VERSION' — must match ^[0-9]+\\.[0-9]+\\.[0-9]+\$" >&2
  exit 1
fi

if [ -n "$VERSION" ] && [ -z "$SHA256" ]; then
  echo "ERROR: release mode requires <sha256> as the second argument" >&2
  exit 1
fi

if [ -n "$SHA256" ] && ! [[ "$SHA256" =~ ^[0-9a-f]{64}$ ]]; then
  echo "ERROR: invalid sha256 '$SHA256' — must be 64 lowercase hex chars" >&2
  exit 1
fi

# ubrn names the podspec after the trimmed-and-camelCased package name
# (`react-native-clear-signing` -> `ClearSigning.podspec`). Autolinking expects
# `<package_name>.podspec`, so we keep `react-native-clear-signing.podspec` as
# the canonical file and delete ubrn's stray ClearSigning.podspec on every run.
rm -f "$PKG_DIR/ClearSigning.podspec"

if [ -n "$VERSION" ]; then
  PREPARE_BLOCK=$(cat <<RELEASE_PREP

  s.prepare_command = <<-SCRIPT
    set -euo pipefail
    ZIP_NAME="libclear_signing-rn.xcframework.zip"
    URL="https://github.com/llbartekll/clear-signing/releases/download/${VERSION}/\${ZIP_NAME}"
    EXPECTED_SHA="${SHA256}"
    STAGING="\$(mktemp -d -t clear-signing.XXXXXX)"
    trap 'rm -rf "\$STAGING"' EXIT
    curl --fail --location --retry 3 --retry-delay 5 --output "\$STAGING/\$ZIP_NAME" "\$URL"
    ACTUAL_SHA="\$(shasum -a 256 "\$STAGING/\$ZIP_NAME" | awk '{print \$1}')"
    if [ "\$ACTUAL_SHA" != "\$EXPECTED_SHA" ]; then
      echo "checksum mismatch for \$ZIP_NAME: expected \$EXPECTED_SHA got \$ACTUAL_SHA" >&2
      exit 1
    fi
    unzip -q "\$STAGING/\$ZIP_NAME" -d "\$STAGING"
    if [ ! -f "\$STAGING/ClearSigning.xcframework/Info.plist" ]; then
      echo "downloaded archive missing ClearSigning.xcframework/Info.plist" >&2
      exit 1
    fi
    rm -rf ClearSigning.xcframework
    mv "\$STAGING/ClearSigning.xcframework" ./ClearSigning.xcframework
  SCRIPT
RELEASE_PREP
)
else
  PREPARE_BLOCK=""
fi

cat > "$PODSPEC" <<PODSPEC_EOF
# Generated by scripts/prepare-rn-podspec.sh — do not edit by hand.
# Regenerate via:
#   ./scripts/prepare-rn-podspec.sh                       (local dev)
#   ./scripts/prepare-rn-podspec.sh <version> <sha256>    (release)
require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))
folly_compiler_flags = '-DFOLLY_NO_CONFIG -DFOLLY_MOBILE=1 -DFOLLY_USE_LIBCPP=1 -Wno-comma -Wno-shorten-64-to-32'

Pod::Spec.new do |s|
  s.name         = "react-native-clear-signing"
  s.version      = package["version"]
  s.summary      = package["description"]
  s.homepage     = package["homepage"]
  s.license      = package["license"]
  s.authors      = package["author"]

  s.platforms    = { :ios => defined?(min_ios_version_supported) ? min_ios_version_supported : '13.4' }
  s.source       = { :git => "https://github.com/llbartekll/clear-signing.git", :tag => "#{s.version}" }

  s.source_files = "ios/**/*.{h,m,mm,swift}", "cpp/**/*.{hpp,cpp,c,h}"
  s.vendored_frameworks = "ClearSigning.xcframework"
${PREPARE_BLOCK}
  # uniffi-bindgen-react-native is intentionally NOT declared here. Consumers
  # must add it to their app Podfile because pulling its podspec transitively
  # via s.dependency conflicts with autolinking resolution. Add to your Podfile:
  #   pod 'uniffi-bindgen-react-native', :path => '../node_modules/uniffi-bindgen-react-native'

  if respond_to?(:install_modules_dependencies, true)
    install_modules_dependencies(s)
  else
    s.dependency "React-Core"
    if ENV['RCT_NEW_ARCH_ENABLED'] == '1' then
      s.compiler_flags = folly_compiler_flags + " -DRCT_NEW_ARCH_ENABLED=1"
      s.pod_target_xcconfig = {
          "HEADER_SEARCH_PATHS" => "\"\$(PODS_ROOT)/boost\"",
          "OTHER_CPLUSPLUSFLAGS" => "-DFOLLY_NO_CONFIG -DFOLLY_MOBILE=1 -DFOLLY_USE_LIBCPP=1",
          "CLANG_CXX_LANGUAGE_STANDARD" => "c++17"
      }
      s.dependency "React-Codegen"
      s.dependency "RCT-Folly"
      s.dependency "RCTRequired"
      s.dependency "RCTTypeSafety"
      s.dependency "ReactCommon/turbomodule/core"
    end
  end
end
PODSPEC_EOF

if [ -n "$VERSION" ]; then
  echo "wrote $PODSPEC (release mode, version=$VERSION sha256=${SHA256:0:12}…)"
else
  echo "wrote $PODSPEC (local-dev mode)"
fi
