// Generated by uniffi-bindgen-react-native
#include "react-native-clear-signing.h"
#include "clear_signing.hpp"

namespace clearsigning {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeClearSigning::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}